export { default as FlagEn } from './flag_en.svg'
export { default as FlagVi } from './flag_vi.svg'
export { default as LogoIcon } from './logo.svg'
export { default as SearchIcon } from './search-icon.svg'
export { default as NotificationIcon } from './notification.svg'
export { default as ExploreIcon } from './explorer.svg'
export { default as MoreIcon } from './more.svg'
export { default as AddListIcon } from './add_list.svg'
export { default as DownloadIcon } from './download.svg'
export { default as ReportIcon } from './report.svg'
export { default as ShareIcon } from './share.svg'
export { default as StopIcon } from './stop.svg'
export { default as HomeIcon } from './home.svg'
export { default as HeartIcon } from './heart.svg'
export { default as LiveIcon } from './live.svg'
export { default as UserIcon } from './users.svg'
export { default as UsersIcon } from './users.svg'
export { default as LotusIcon } from './lotus.svg'
export { default as LeftArrowIcon } from './left_arrow.svg'
export { default as PlayIcon } from './play.svg'
export { default as PlaySmall } from './play_small.svg'
export { default as PauseIcon } from './pause.svg'
import DownArrow from './down_arrow.svg'
import UpArrow from './up_arrow.svg'
export { default as FullscreenIcon } from './full_screen.svg'
export { default as SmallScreenIcon } from './small_screen.svg'
export { default as LoadingIcon } from './loading.svg'
export { default as SpeedArrowIcon } from './speed_arrow.svg'
export { default as ChevronDownIcon } from './chevron_down.svg'
export { default as MessageIcon } from './message_box.svg'
export { default as LockedIcon } from './locked.svg'
export { default as UnlockedIcon } from './unlocked.svg'
export { default as VolumeIcon } from './volume.svg'
export { default as VolumeFillIcon } from './volume_fill.svg'
export { default as VolumeFillMuteIcon } from './volume_fill_mute.svg'
export { default as VolumeLiveIcon } from './volume_live.svg'
export { default as FireIcon } from './fire.svg'
export { default as FireWhiteIcon } from './fire_white.svg'
export { default as FastBackwardIcon } from './fast_backward.svg'
export { default as FastForwardIcon } from './fast_forward.svg'
export { default as Volume1Icon } from './volume_1.svg'
export { default as Volume2Icon } from './volume_2.svg'
export { default as Volume3Icon } from './volume_3.svg'
export { default as MuteIcon } from './mute.svg'
export { default as AddIcon } from './add.svg'
export { default as SortListIcon } from './sort_list.svg'
export { default as EmojiIcon } from './emoji.svg'
export { default as SendIcon } from './send.svg'
export { default as SettingIcon } from './settings.svg'
export { default as SettingFillIcon } from './setting-fill.svg'
export { default as PlaybackSpeedIcon } from './playback_speed.svg'
export { default as ClockIcon } from './clock.svg'
export { default as DeleteIcon } from './delete_icon.svg'
export { default as EditPen } from './edit_pen.svg'
export { default as ShareLinkIcon } from './shareLink.svg'
export { default as MessageFacebookIcon } from './messenger.svg'
export { default as TwitterIcon } from './twitter.svg'
export { default as GoogleIcon } from './google.svg'
export { default as TelegramIcon } from './telegram.svg'
export { default as SquareIcon } from './square.svg'
export { default as SquareEmptyIcon } from './square_empty.svg'
export { default as CheckIcon } from './check.svg'
export { default as ShareFillIcon } from './share_fill.svg'
export { default as RefreshIcon } from './refresh.svg'
export { default as FacebookIcon } from './facebook.svg'
export { default as FacebookBlueIcon } from './facebook-blue.svg'
export { default as DirectionsIcon } from './directions.svg'
export { default as MoreHorizontalIcon } from './more_horizontal.svg'
export { default as WatchLaterFillIcon } from './watch-later.svg'
import CommentIcon from './comment.svg'
import CloseIcon from './close.svg'
import LogoAdvertisementLogo from './logo_adventisement.svg'
import ViewIcon from './view.svg'
export { default as CloseFillIcon } from './close_fill.svg'
export { default as HeartFilled } from './heart_filled.svg'
export { default as ActiveHome } from './home_filled.svg'
export { default as RadioChecked } from './radio_checked.svg'
export { default as BlockChatIcon } from './block_chat.svg'
export { default as CheckRoundIcon } from './checkboxRound.svg'
export { default as PinIcon } from './pin.svg'
export { default as ReplyIcon } from './reply.svg'
export { default as WrenchIcon } from './wrench.svg'
export { default as RadioEmpty } from './radio_empty.svg'
export { default as PhimIcon } from './phim.svg'
export { default as DefaultAvavar } from './default_avatar.svg'
export { default as DefaultBanner } from './default_banner.svg'
export { default as DefaultPosterShort } from './default_poster_short.svg'
export { default as StarCategoryIcon } from './star-category.svg'
export { default as DonateIcon } from './donate.svg'
export { default as LiveChatIcon } from './live_chats.svg'
export { default as DollarIcon } from './dollar.svg'
export { default as CashIcon } from './cash.svg'
export { default as CrownIcon } from './crown.svg'
export { default as CameraOnIcon } from './camera_on.svg'
export { default as CameraUpLoadImgIcon } from './camera_upload_img.svg'
export { default as HeartMenuIcon } from './heart_menu.svg'
export { default as UserCheckedIcon } from './user_check.svg'
export { default as RecentIcon } from './recent_clock.svg'
export { default as WatchLaterIcon } from './watch_later_clock.svg'
export { default as ListMenuIcon } from './list_menu.svg'
export { default as LinkIcon } from './link.svg'
export { default as LockedMenuIcon } from './locked_menu.svg'
export { default as DocumentIcon } from './document.svg'
export { default as ShieldIcon } from './shield.svg'
export { default as BookIcon } from './book.svg'
export { default as ContactIcon } from './contact.svg'
export { default as LogoutIcon } from './log_out.svg'
export { default as ZaloIcon } from './zalo.svg'
export { default as MessageFilledIcon } from './message_filled.svg'
export { default as FilterIcon } from './filter.svg'
export { default as HeartFilledColor } from './heartfill.svg'
export { default as HeartRedIcon } from './heart_red.svg'
export { default as HappyIcon } from './happy.svg'
export { default as TreasureIcon } from './treasure.svg'
export { default as GiftIcon } from './gift.svg'
export { default as StarIcon } from './star.svg'
export { default as EyeIcon } from './eye.svg'
export { default as ReloadIcon } from './reload.svg'
import GooglePlay from './Google Play.png'
import AppStore from './App Store.png'
import BoCongThuong from './BoCongThuong.png'
export { default as LogoLoginIcon } from './LogoLogin.svg'
export { default as FourGIcon } from './4G.svg'
export { default as AppleIcon } from './apple.svg'
export { default as BellIcon } from './bell.svg'
export { default as NotiOffIcon } from './notification_off.svg'
export { default as ListEmptyIcon } from './list_empty.svg'
export { default as PlayListIcon } from './playlist.svg'
export { default as Pen2Icon } from './pen2.svg'
export { default as RepeatIcon } from './repeat.svg'
export { default as ShuffleIcon } from './shuffle.svg'
export { default as DownFillIcon } from './down-fill.svg'
export { default as CameraIcon } from './camera.svg'
export { default as CloseCircleIcon } from './close_circle.svg'
export { default as SaveIcon } from './save.svg'
export { default as CheckboxIcon } from './checkbox.svg'
export { default as ChangeePasswordIcon } from './changee_password.svg'
export { default as EyeOffIcon } from './eye_off.svg'
export { default as NotFoundIcon } from './404.svg'
export { default as UploadBigIcon } from './upload-big.svg'
export { default as HourglasscCon } from './hourglass.svg'
export { default as AccountIcon } from './account.svg'
export { default as UpArrowRounded } from './up_arrow_rounded.svg'
export { default as PhoneIcon } from './iphone.svg'
export { default as MarkReadIcon } from './mark_as_read.svg'
export { default as MyclipSvgIcon } from './myclip-icon.svg'
export { default as MyclipIcon } from './myclip.svg'
export { default as CircleStudioIcon } from './circle_studio.svg'
export { default as WrenchOutlineIcon } from './wrench_outline.svg'
export { default as NoteIcon } from './note.svg'
export { default as MicroIcon } from './micro.svg'
export { default as CloseSmallIcon } from './close_sm.svg'
export { default as MonopolyIcon } from './monopoly.svg'
export { default as KaraokeIcon } from './karaoke_icon.svg'
// export { default as MyclipIcon } from './myclip.svg'
export {
  DownArrow,
  UpArrow,
  CommentIcon,
  CloseIcon,
  LogoAdvertisementLogo,
  ViewIcon,
  GooglePlay,
  AppStore,
  BoCongThuong,
}
