
export const FAKE_DATA = [
    {
        id: 3642468,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642467,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [
            {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            }, {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            },
        ],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642466,
        comment: 'dsadsadsa dsad asd sadsa ',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642465,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642351,
        comment: 'phim hay qua, test test test test playlist',
        channel: null,
        createdAt: '23 ngày trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 1,
    },
    {
        id: 3642468,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642467,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [
            {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            },
        ],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642466,
        comment: 'dsadsadsa dsad asd sadsa ',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642465,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642351,
        comment: 'phim hay qua, test test test test playlist',
        channel: null,
        createdAt: '23 ngày trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 1,
    }, {
        id: 3642468,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642467,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [
            {
                id: 3642469,
                comment: 'dsadsad dsadsa dsad as ddsadsadsad saa',
                channel: null,
                createdAt: '11 giờ trước',
                children: [],
                commentCount: 0,
                likeCount: 0,
                status: 0,
            },
        ],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642466,
        comment: 'dsadsadsa dsad asd sadsa ',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642465,
        comment: 'dsadsadsa dsad asd sadsa',
        channel: null,
        createdAt: '17 giờ trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 0,
    },
    {
        id: 3642351,
        comment: 'phim hay qua, test test test test playlist',
        channel: null,
        createdAt: '23 ngày trước',
        children: [],
        commentCount: 0,
        likeCount: 0,
        status: 1,
    },
]