export const DATE_TIME_FORMAT = 'HH:mm DD/MM/YYYY'
export const DATE_FORMAT = 'DD/MM/YYYY'
export const DATE_FORMAT_2 = 'YYYY-MM-DD'
export const TIME_FORMAT = 'HH:mm'
export const BE_DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss.SSSSZ'
